//Maya ASCII 2024 scene
//Name: mPyMesh_text.ma
//Last modified: Wed, Jul 08, 2026 12:16:15 AM
//Codeset: UTF-8
requires maya "2024";
requires -nodeType "mPyMesh" "mpynode_api2.py" "1.0.0a1";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2024";
fileInfo "version" "2024";
fileInfo "cutIdentifier" "202511121304-3e6f4fc3f6";
fileInfo "osv" "Mac OS X 20.5.1";
fileInfo "UUID" "E3C51661-D04F-83C2-D169-898875D37645";
createNode transform -s -n "persp";
	rename -uid "22F4545C-604B-333E-29B6-279777E4061A";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 28 21 28 ;
	setAttr ".r" -type "double3" -27.938352729602379 44.999999999999972 -5.172681101354183e-14 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "24800D19-574B-D911-61D8-99BE881D506F";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999986;
	setAttr ".coi" 44.82186966202994;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "3BBFE741-BA4C-365B-BD1A-89BDC78A3B5F";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "8CDE2D0D-3C42-4AFC-E13B-EA9FB25650DB";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	rename -uid "4F63D36C-F14F-7D12-D521-7A98B40F3517";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "F75EBACB-F849-16FA-876C-0FB3025435B3";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	rename -uid "FA0282BC-CB4A-7241-C783-3EA6F7DC2EF7";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "F86547F1-E546-E77E-94DF-2BA2BEA84849";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode transform -n "textStrokes";
	rename -uid "88B2FFD8-5541-65F6-C1B7-A38E403388EF";
createNode transform -n "stroke00" -p "textStrokes";
	rename -uid "F9BBA9AC-2F49-C494-086A-EA99C7898308";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -4.4500000000000011 0.7 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.80999999999999994 0.11 0.25 ;
createNode transform -n "stroke01" -p "textStrokes";
	rename -uid "4FC06201-DF44-D92C-7FE0-4DA93B7C2373";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -3.6500000000000008 0.7 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.80999999999999994 0.11 0.25 ;
createNode transform -n "stroke02" -p "textStrokes";
	rename -uid "CEE0A1B2-DC4C-2679-CC1D-71A70347767E";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -4.2500000000000009 0.975 0 ;
	setAttr ".r" -type "double3" 0 0 -64.798876354524921 ;
	setAttr ".halfExtents" -type "double3" 0.57970735570139831 0.11 0.25 ;
createNode transform -n "stroke03" -p "textStrokes";
	rename -uid "859D7ACD-6244-66A2-B50E-9BB37862422C";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -3.8500000000000005 0.975 0 ;
	setAttr ".r" -type "double3" 0 0 -115.20112364547508 ;
	setAttr ".halfExtents" -type "double3" 0.57970735570139831 0.11 0.25 ;
createNode transform -n "stroke04" -p "textStrokes";
	rename -uid "89C95ACE-174B-DC89-1DF1-2F8372775612";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -3.1000000000000005 0.7 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.80999999999999994 0.11 0.25 ;
createNode transform -n "stroke05" -p "textStrokes";
	rename -uid "829379A5-3E45-A55C-5D30-D29FF50FE60B";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -2.7500000000000004 1.4 0 ;
	setAttr ".halfExtents" -type "double3" 0.46 0.11 0.25 ;
createNode transform -n "stroke06" -p "textStrokes";
	rename -uid "E87D3D5B-5449-7E25-072D-488A6A8EB87F";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -2.4000000000000004 1.06 0 ;
	setAttr ".r" -type "double3" 0 0 -90 ;
	setAttr ".halfExtents" -type "double3" 0.44999999999999996 0.11 0.25 ;
createNode transform -n "stroke07" -p "textStrokes";
	rename -uid "69617AD7-A84D-DEB8-057E-DA8C7EBD066A";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -2.7500000000000004 0.72 0 ;
	setAttr ".halfExtents" -type "double3" 0.46 0.11 0.25 ;
createNode transform -n "stroke08" -p "textStrokes";
	rename -uid "CCFB9019-6145-47BC-9AB1-8EACDA47C1B6";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -1.5400000000000005 0.615 0 ;
	setAttr ".r" -type "double3" 0 0 -60.439645535319265 ;
	setAttr ".halfExtents" -type "double3" 0.49512984823303419 0.11 0.25 ;
createNode transform -n "stroke09" -p "textStrokes";
	rename -uid "A560CC17-AA41-486C-0BA1-CD8C766E4EA5";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -1.2700000000000005 0.19999999999999996 0 ;
	setAttr ".r" -type "double3" 0 0 -111.80140948635182 ;
	setAttr ".halfExtents" -type "double3" 0.91777472107017555 0.11 0.25 ;
createNode transform -n "stroke10" -p "textStrokes";
	rename -uid "4674BBB3-0F45-BD7E-690B-E7A353CB6E3A";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" -0.4 0.7 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.80999999999999994 0.11 0.25 ;
createNode transform -n "stroke11" -p "textStrokes";
	rename -uid "3D34A281-C445-C068-2DEA-8CA4D92610DD";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 0.4 0.7 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.80999999999999994 0.11 0.25 ;
createNode transform -n "stroke12" -p "textStrokes";
	rename -uid "015F52B4-B34C-4E6C-A889-18A04CCF043D";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 0 0.7 0 ;
	setAttr ".r" -type "double3" 0 0 -60.255118703057768 ;
	setAttr ".halfExtents" -type "double3" 0.9162257748298549 0.11 0.25 ;
createNode transform -n "stroke13" -p "textStrokes";
	rename -uid "196FD29D-6444-1EF8-A1A5-46A14591DB78";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 1.3499999999999996 0 0 ;
	setAttr ".halfExtents" -type "double3" 0.49 0.11 0.25 ;
createNode transform -n "stroke14" -p "textStrokes";
	rename -uid "8C9DC164-E94D-773B-5670-9AAA7D0345E8";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 1.3499999999999996 0.95 0 ;
	setAttr ".halfExtents" -type "double3" 0.49 0.11 0.25 ;
createNode transform -n "stroke15" -p "textStrokes";
	rename -uid "F19B49A7-514A-E1E2-46A8-D9A8C24BE886";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 0.96999999999999964 0.475 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.585 0.11 0.25 ;
createNode transform -n "stroke16" -p "textStrokes";
	rename -uid "DE4E75EB-1940-459D-599C-9EAE0200FA6A";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 1.7299999999999995 0.475 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.585 0.11 0.25 ;
createNode transform -n "stroke17" -p "textStrokes";
	rename -uid "1C2A7837-3B43-9119-A0D9-9BB53A52CADB";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 3.0799999999999992 0.7 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.80999999999999994 0.11 0.25 ;
createNode transform -n "stroke18" -p "textStrokes";
	rename -uid "F3CEEA73-8843-A9F8-7A4B-72AF5C8DE39D";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 2.3199999999999994 0.475 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.585 0.11 0.25 ;
createNode transform -n "stroke19" -p "textStrokes";
	rename -uid "03FB8302-5F45-5556-9E1C-FD9811053EFC";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 2.6999999999999993 0.95 0 ;
	setAttr ".halfExtents" -type "double3" 0.49 0.11 0.25 ;
createNode transform -n "stroke20" -p "textStrokes";
	rename -uid "850ED52B-F24E-2941-3F35-3C8AADF36F36";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 2.6999999999999993 0 0 ;
	setAttr ".halfExtents" -type "double3" 0.49 0.11 0.25 ;
createNode transform -n "stroke21" -p "textStrokes";
	rename -uid "42B91FB4-494F-5140-2597-3FB47D5DB7EB";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 3.6700000000000008 0.475 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.585 0.11 0.25 ;
createNode transform -n "stroke22" -p "textStrokes";
	rename -uid "4F1C25F5-5045-C5B1-FA38-548CA1FECB13";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 4.0500000000000007 0.95 0 ;
	setAttr ".halfExtents" -type "double3" 0.49 0.11 0.25 ;
createNode transform -n "stroke23" -p "textStrokes";
	rename -uid "AFBF481E-B04C-4AF6-57C5-A69AB6A057D0";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 4.0500000000000007 0.475 0 ;
	setAttr ".halfExtents" -type "double3" 0.49 0.11 0.25 ;
createNode transform -n "stroke24" -p "textStrokes";
	rename -uid "FDA8B5A9-6141-C29E-6E81-B6ACD6F4C446";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 4.0500000000000007 0 0 ;
	setAttr ".halfExtents" -type "double3" 0.49 0.11 0.25 ;
createNode transform -n "stroke25" -p "textStrokes";
	rename -uid "6B9EDA6D-F643-DEE6-C372-1993F8BE93B7";
	addAttr -ci true -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	setAttr ".t" -type "double3" 4.4300000000000006 0.71249999999999991 0 ;
	setAttr ".r" -type "double3" 0 0 90 ;
	setAttr ".halfExtents" -type "double3" 0.3475 0.11 0.25 ;
createNode transform -n "sdfTextRender";
	rename -uid "E89E0F99-C84F-0DF0-8336-5A9E6895D56A";
createNode mesh -n "sdfTextRenderShape" -p "sdfTextRender";
	rename -uid "BEC5DB8D-A943-D26B-04BE-99BCB34A663E";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "D8880C01-6D43-938E-B847-D99BB68C1DDD";
	setAttr -s 2 ".lnk";
	setAttr -s 2 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "A9C09EBA-D54B-67B7-AC67-86A858B82436";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "A7189579-1C4D-8C72-DA7D-499D5F8EE042";
createNode displayLayerManager -n "layerManager";
	rename -uid "7936A986-2243-B3EF-6BEA-0F9E8FEB28CC";
createNode displayLayer -n "defaultLayer";
	rename -uid "D88957A0-184C-1462-66B4-A29D7F8FD969";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "07BC9666-EB4F-5F25-A96D-A0B9FE950B8F";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "B110F6F0-D345-02E5-D54F-7E94C8228CD2";
	setAttr ".g" yes;
createNode mPyMesh -n "sdfText";
	rename -uid "01DAB745-4348-BF90-0A3D-F98AB00622C6";
	addAttr -ci true -k true -m -sn "shapeMatrix" -ln "shapeMatrix" -dt "matrix";
	addAttr -ci true -k true -m -sn "shapeType" -ln "shapeType" -at "long";
	addAttr -ci true -k true -m -sn "additive" -ln "additive" -min 0 -max 1 -at "bool";
	addAttr -ci true -k true -m -sn "smoothing" -ln "smoothing" -at "double";
	addAttr -ci true -k true -m -sn "radius" -ln "radius" -at "double";
	addAttr -ci true -k true -m -sn "height" -ln "height" -at "double";
	addAttr -ci true -k true -m -sn "axis" -ln "axis" -at "long";
	addAttr -ci true -k true -m -sn "halfExtents" -ln "halfExtents" -at "double3" -nc 
		3;
	addAttr -ci true -k true -sn "halfExtentsX" -ln "halfExtentsX" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsY" -ln "halfExtentsY" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "halfExtentsZ" -ln "halfExtentsZ" -at "double" -p "halfExtents";
	addAttr -ci true -k true -sn "resolution" -ln "resolution" -dv 8 -at "long";
	addAttr -ci true -k true -sn "isoValue" -ln "isoValue" -at "double";
	addAttr -ci true -h true -sn "_initSource" -ln "_initSource" -dt "string";
	addAttr -ci true -h true -sn "_methodsSource" -ln "_methodsSource" -dt "string";
	setAttr "._computeSource" -type "string" (
		"mats = np.asarray(self.shapeMatrix, dtype=np.float64)\nif mats.ndim != 3 or mats.shape[0] == 0:\n    pts = np.zeros((0, 3), dtype=np.float64)\n    cnts = np.zeros(0, dtype=np.int32)\n    idx = np.zeros(0, dtype=np.int32)\nelse:\n    n = mats.shape[0]\n    shape_type = _read_dense(self, \"shapeType\", np.zeros(n, dtype=np.int64))\n    additive = _read_dense(self, \"additive\", np.ones(n, dtype=bool))\n    smoothing = _read_dense(self, \"smoothing\", np.zeros(n, dtype=np.float64))\n    radius = _read_dense(self, \"radius\", np.where(shape_type == 2, 0.5, 1.0))\n    height = _read_dense(self, \"height\", np.ones(n, dtype=np.float64))\n    axis = _read_dense(self, \"axis\", np.ones(n, dtype=np.int64))\n    half = _read_dense(self, \"halfExtents\", np.tile([0.5, 0.5, 0.5], (n, 1)))\n    _res = getattr(self, \"resolution\", None)\n    res = 8 if _res is None else int(_res)\n    _iso = getattr(self, \"isoValue\", None)\n    iso = 0.0 if _iso is None else float(_iso)\n    pts, cnts, idx = mesh_from_shapes(\n        mats, shape_type, additive, smoothing, radius, height, axis, half,\n"
		+ "        res, iso,\n    )\nself.points = pts\nself.counts = cnts\nself.indices = idx\nself.outMesh = build_default_output(pts, cnts, idx)\n");
	setAttr "._inputAttrs" -type "string" "{\"additive\":{\"attr_type\":\"bool\",\"is_array\":true,\"order\":2},\"axis\":{\"attr_type\":\"int\",\"is_array\":true,\"order\":6},\"halfExtents\":{\"attr_type\":\"vector\",\"is_array\":true,\"order\":7},\"height\":{\"attr_type\":\"double\",\"is_array\":true,\"order\":5},\"isoValue\":{\"attr_type\":\"double\",\"default_value\":0.0,\"is_array\":false,\"order\":9},\"radius\":{\"attr_type\":\"double\",\"is_array\":true,\"order\":4},\"resolution\":{\"attr_type\":\"int\",\"default_value\":8,\"is_array\":false,\"order\":8},\"shapeMatrix\":{\"attr_type\":\"matrix\",\"is_array\":true,\"order\":0},\"shapeType\":{\"attr_type\":\"int\",\"is_array\":true,\"order\":1},\"smoothing\":{\"attr_type\":\"double\",\"is_array\":true,\"order\":3}}";
	setAttr -s 26 ".shapeMatrix";
	setAttr -k on ".shapeMatrix[0]";
	setAttr -k on ".shapeMatrix[1]";
	setAttr -k on ".shapeMatrix[2]";
	setAttr -k on ".shapeMatrix[3]";
	setAttr -k on ".shapeMatrix[4]";
	setAttr -k on ".shapeMatrix[5]";
	setAttr -k on ".shapeMatrix[6]";
	setAttr -k on ".shapeMatrix[7]";
	setAttr -k on ".shapeMatrix[8]";
	setAttr -k on ".shapeMatrix[9]";
	setAttr -k on ".shapeMatrix[10]";
	setAttr -k on ".shapeMatrix[11]";
	setAttr -k on ".shapeMatrix[12]";
	setAttr -k on ".shapeMatrix[13]";
	setAttr -k on ".shapeMatrix[14]";
	setAttr -k on ".shapeMatrix[15]";
	setAttr -k on ".shapeMatrix[16]";
	setAttr -k on ".shapeMatrix[17]";
	setAttr -k on ".shapeMatrix[18]";
	setAttr -k on ".shapeMatrix[19]";
	setAttr -k on ".shapeMatrix[20]";
	setAttr -k on ".shapeMatrix[21]";
	setAttr -k on ".shapeMatrix[22]";
	setAttr -k on ".shapeMatrix[23]";
	setAttr -k on ".shapeMatrix[24]";
	setAttr -k on ".shapeMatrix[25]";
	setAttr -k on ".shapeMatrix";
	setAttr -s 26 -k on ".shapeType[0:25]"  1 1 1 1 
		1 1 1 1 1 1 1 1 1 1 1 1 
		1 1 1 1 1 1 1 1 1 1;
	setAttr -s 26 -k on ".additive[0:25]" yes yes yes yes yes yes yes yes 
		yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes yes;
	setAttr -k on ".smoothing";
	setAttr -s 26 -k on ".halfExtents";
	setAttr -s 26 -k on ".halfExtents";
	setAttr -k on ".halfExtents[0]";
	setAttr -k on ".halfExtents[1]";
	setAttr -k on ".halfExtents[2]";
	setAttr -k on ".halfExtents[3]";
	setAttr -k on ".halfExtents[4]";
	setAttr -k on ".halfExtents[5]";
	setAttr -k on ".halfExtents[6]";
	setAttr -k on ".halfExtents[7]";
	setAttr -k on ".halfExtents[8]";
	setAttr -k on ".halfExtents[9]";
	setAttr -k on ".halfExtents[10]";
	setAttr -k on ".halfExtents[11]";
	setAttr -k on ".halfExtents[12]";
	setAttr -k on ".halfExtents[13]";
	setAttr -k on ".halfExtents[14]";
	setAttr -k on ".halfExtents[15]";
	setAttr -k on ".halfExtents[16]";
	setAttr -k on ".halfExtents[17]";
	setAttr -k on ".halfExtents[18]";
	setAttr -k on ".halfExtents[19]";
	setAttr -k on ".halfExtents[20]";
	setAttr -k on ".halfExtents[21]";
	setAttr -k on ".halfExtents[22]";
	setAttr -k on ".halfExtents[23]";
	setAttr -k on ".halfExtents[24]";
	setAttr -k on ".halfExtents[25]";
	setAttr -k on ".resolution" 12;
	setAttr "._initSource" -type "string" (
		"import numpy as np\nfrom mpynode._api2.mpy_mesh import build_default_output\nfrom mpynode._common.nodes.mesh.sdf_dmc import mesh_from_shapes\n\n\ndef _read_dense(self, name, defaults):\n    # Overlay a per-shape array input onto the demo's semantic defaults,\n    # returning a dense numpy array of length len(defaults). Every user\n    # array input surfaces as a dense, gap-filled numpy array (unset slots\n    # hold the attribute default) whose POSITION is the logical plug index,\n    # so enumerate() aligns each parallel array by shape. Matrix inputs\n    # surface as a numpy-transparent MatrixArrayView; vector inputs as an\n    # (m, 3) float array. All reads are EM-safe (datablock-backed).\n    proxy = getattr(self, name, None)\n    out = np.array(defaults)\n    n = out.shape[0]\n    if proxy is None or n == 0:\n        return out\n    is_vec = out.ndim > 1\n    try:\n        for idx, elem in enumerate(proxy):\n            if idx >= n:\n                break\n            out[idx] = np.asarray(elem, dtype=out.dtype) if is_vec else elem\n    except TypeError:\n"
		+ "        pass\n    return out\n");
	setAttr "._methodsSource" -type "string" (
		"from mpynode._common.methods.maya_command import maya_command\n\n\ndef _resolve_transform(transform):\n    # Resolve the transform to wire: the explicit arg, else the first\n    # selected transform, else a freshly created one.\n    from maya import cmds as mc\n    if transform is not None:\n        return transform\n    sel = mc.ls(selection=True, long=True, type=\"transform\") or []\n    return sel[0] if sel else mc.createNode(\"transform\", name=\"sdfShape#\")\n\n\ndef _next_index(node):\n    # Next free logical index on shapeMatrix; the SDF fold order IS the\n    # array index, so always append past the current max (gap-safe).\n    from maya import cmds as mc\n    idxs = mc.getAttr(node + \".shapeMatrix\", multiIndices=True) or []\n    return (max(idxs) + 1) if idxs else 0\n\n\ndef _ensure_double(transform, name, value):\n    # Add a keyable double attr (default = value) to the transform if it is\n    # missing, then set it. Returns the plug to connect.\n    from maya import cmds as mc\n    if not mc.attributeQuery(name, node=transform, exists=True):\n"
		+ "        mc.addAttr(transform, longName=name, attributeType=\"double\",\n                   defaultValue=float(value), keyable=True)\n    mc.setAttr(transform + \".\" + name, float(value))\n    return transform + \".\" + name\n\n\ndef _ensure_double3(transform, name, values):\n    # Add a keyable double3 compound (e.g. box half-extents) if missing,\n    # then set it. Returns the parent plug to connect.\n    from maya import cmds as mc\n    if not mc.attributeQuery(name, node=transform, exists=True):\n        mc.addAttr(transform, longName=name, attributeType=\"double3\")\n        for ax in (\"X\", \"Y\", \"Z\"):\n            mc.addAttr(transform, longName=name + ax, attributeType=\"double\",\n                       parent=name, keyable=True)\n    mc.setAttr(transform + \".\" + name, *(float(v) for v in values),\n               type=\"double3\")\n    return transform + \".\" + name\n\n\ndef _begin_shape(self, transform, shape_type, additive, smoothing):\n    # Shared wiring for every add*: resolve the transform, claim the next\n    # index, connect its worldMatrix into shapeMatrix, and stamp the common\n"
		+ "    # per-shape CSG flags. Returns (node, transform, idx).\n    from maya import cmds as mc\n    node = self.get_name()\n    transform = _resolve_transform(transform)\n    idx = _next_index(node)\n    mc.connectAttr(transform + \".worldMatrix[0]\",\n                   \"%s.shapeMatrix[%d]\" % (node, idx), force=True)\n    mc.setAttr(\"%s.shapeType[%d]\" % (node, idx), int(shape_type))\n    mc.setAttr(\"%s.additive[%d]\" % (node, idx), int(bool(additive)))\n    mc.setAttr(\"%s.smoothing[%d]\" % (node, idx), float(smoothing))\n    return node, transform, idx\n\n\n@maya_command\ndef addSphere(self, transform=None, radius=1.0, additive=True, smoothing=0.0):\n    from maya import cmds as mc\n    node, transform, idx = _begin_shape(self, transform, 0, additive, smoothing)\n    plug = _ensure_double(transform, \"radius\", radius)\n    mc.connectAttr(plug, \"%s.radius[%d]\" % (node, idx), force=True)\n    return transform\n\n\n@maya_command\ndef addBox(self, transform=None, half=(0.5, 0.5, 0.5), additive=True,\n           smoothing=0.0):\n    from maya import cmds as mc\n"
		+ "    node, transform, idx = _begin_shape(self, transform, 1, additive, smoothing)\n    plug = _ensure_double3(transform, \"halfExtents\", half)\n    mc.connectAttr(plug, \"%s.halfExtents[%d]\" % (node, idx), force=True)\n    return transform\n\n\n@maya_command\ndef addCylinder(self, transform=None, radius=0.5, height=1.0, axis=1,\n                additive=True, smoothing=0.0):\n    from maya import cmds as mc\n    node, transform, idx = _begin_shape(self, transform, 2, additive, smoothing)\n    rplug = _ensure_double(transform, \"radius\", radius)\n    hplug = _ensure_double(transform, \"height\", height)\n    mc.connectAttr(rplug, \"%s.radius[%d]\" % (node, idx), force=True)\n    mc.connectAttr(hplug, \"%s.height[%d]\" % (node, idx), force=True)\n    mc.setAttr(\"%s.axis[%d]\" % (node, idx), int(axis))\n    return transform\n\n\n\"\"\"Setup source for mPyMesh nodes (self-first instance method).\"\"\"\n\ndef setup(self, *args, **kwargs):\n    from maya import cmds as mc\n    name = self.get_name()\n    # build() owns ``self`` -- never delete it on failure. Only roll back the\n"
		+ "    # render transform/shape this body creates so a partial failure leaves no\n    # *Render / *RenderShape orphan (self is left built-but-unwired); re-raise.\n    created = []\n    conn = None  # (src, dst) we wired; break it before delete so the rollback\n                 # doesn't cascade-delete the upstream ``self``.\n    try:\n        xform = mc.createNode(\"transform\", name=name + \"Render\"); created.append(xform)\n        shape = mc.createNode(\"mesh\", name=name + \"RenderShape\", parent=xform)\n        src, dst = name + \".outMesh\", shape + \".inMesh\"\n        mc.connectAttr(src, dst, force=True); conn = (src, dst)\n        mc.sets(shape, edit=True, forceElement=\"initialShadingGroup\")\n        return name\n    except Exception:\n        if conn:\n            try:\n                mc.disconnectAttr(conn[0], conn[1])\n            except Exception:\n                pass\n        if created:\n            mc.delete([n for n in created if mc.objExists(n)])\n        raise\n");
createNode script -n "uiConfigurationScriptNode";
	rename -uid "49316EA1-DD43-9A62-AB33-5D8FB0134133";
	setAttr ".b" -type "string" "// Maya Mel UI Configuration File.\n// No UI generated in batch mode.\n";
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "6F2A5AD9-BC4D-0EA2-E60D-2DBC9A6E26DB";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 120 -ast 1 -aet 200 ";
	setAttr ".st" 6;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 3;
select -ne :renderPartition;
	setAttr -s 2 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 5 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".dss" -type "string" "standardSurface1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "sdfText.om" "sdfTextRenderShape.i";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "stroke00.wm" "sdfText.shapeMatrix[0]";
connectAttr "stroke01.wm" "sdfText.shapeMatrix[1]";
connectAttr "stroke02.wm" "sdfText.shapeMatrix[2]";
connectAttr "stroke03.wm" "sdfText.shapeMatrix[3]";
connectAttr "stroke04.wm" "sdfText.shapeMatrix[4]";
connectAttr "stroke05.wm" "sdfText.shapeMatrix[5]";
connectAttr "stroke06.wm" "sdfText.shapeMatrix[6]";
connectAttr "stroke07.wm" "sdfText.shapeMatrix[7]";
connectAttr "stroke08.wm" "sdfText.shapeMatrix[8]";
connectAttr "stroke09.wm" "sdfText.shapeMatrix[9]";
connectAttr "stroke10.wm" "sdfText.shapeMatrix[10]";
connectAttr "stroke11.wm" "sdfText.shapeMatrix[11]";
connectAttr "stroke12.wm" "sdfText.shapeMatrix[12]";
connectAttr "stroke13.wm" "sdfText.shapeMatrix[13]";
connectAttr "stroke14.wm" "sdfText.shapeMatrix[14]";
connectAttr "stroke15.wm" "sdfText.shapeMatrix[15]";
connectAttr "stroke16.wm" "sdfText.shapeMatrix[16]";
connectAttr "stroke17.wm" "sdfText.shapeMatrix[17]";
connectAttr "stroke18.wm" "sdfText.shapeMatrix[18]";
connectAttr "stroke19.wm" "sdfText.shapeMatrix[19]";
connectAttr "stroke20.wm" "sdfText.shapeMatrix[20]";
connectAttr "stroke21.wm" "sdfText.shapeMatrix[21]";
connectAttr "stroke22.wm" "sdfText.shapeMatrix[22]";
connectAttr "stroke23.wm" "sdfText.shapeMatrix[23]";
connectAttr "stroke24.wm" "sdfText.shapeMatrix[24]";
connectAttr "stroke25.wm" "sdfText.shapeMatrix[25]";
connectAttr "stroke00.halfExtents" "sdfText.halfExtents[0]";
connectAttr "stroke01.halfExtents" "sdfText.halfExtents[1]";
connectAttr "stroke02.halfExtents" "sdfText.halfExtents[2]";
connectAttr "stroke03.halfExtents" "sdfText.halfExtents[3]";
connectAttr "stroke04.halfExtents" "sdfText.halfExtents[4]";
connectAttr "stroke05.halfExtents" "sdfText.halfExtents[5]";
connectAttr "stroke06.halfExtents" "sdfText.halfExtents[6]";
connectAttr "stroke07.halfExtents" "sdfText.halfExtents[7]";
connectAttr "stroke08.halfExtents" "sdfText.halfExtents[8]";
connectAttr "stroke09.halfExtents" "sdfText.halfExtents[9]";
connectAttr "stroke10.halfExtents" "sdfText.halfExtents[10]";
connectAttr "stroke11.halfExtents" "sdfText.halfExtents[11]";
connectAttr "stroke12.halfExtents" "sdfText.halfExtents[12]";
connectAttr "stroke13.halfExtents" "sdfText.halfExtents[13]";
connectAttr "stroke14.halfExtents" "sdfText.halfExtents[14]";
connectAttr "stroke15.halfExtents" "sdfText.halfExtents[15]";
connectAttr "stroke16.halfExtents" "sdfText.halfExtents[16]";
connectAttr "stroke17.halfExtents" "sdfText.halfExtents[17]";
connectAttr "stroke18.halfExtents" "sdfText.halfExtents[18]";
connectAttr "stroke19.halfExtents" "sdfText.halfExtents[19]";
connectAttr "stroke20.halfExtents" "sdfText.halfExtents[20]";
connectAttr "stroke21.halfExtents" "sdfText.halfExtents[21]";
connectAttr "stroke22.halfExtents" "sdfText.halfExtents[22]";
connectAttr "stroke23.halfExtents" "sdfText.halfExtents[23]";
connectAttr "stroke24.halfExtents" "sdfText.halfExtents[24]";
connectAttr "stroke25.halfExtents" "sdfText.halfExtents[25]";
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
connectAttr "sdfTextRenderShape.iog" ":initialShadingGroup.dsm" -na;
// End of mPyMesh_text.ma
