//Maya ASCII 2024 scene
//Name: sphereWaveFromLocator.ma
//Last modified: Sat, Jul 11, 2026 12:14:10 AM
//Codeset: UTF-8
requires maya "2024";
requires -nodeType "mPyDeformer" "mpynode_api1.py" "1.0.0a1";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2024";
fileInfo "version" "2024";
fileInfo "cutIdentifier" "202511121304-3e6f4fc3f6";
fileInfo "osv" "Mac OS X 20.5.1";
fileInfo "UUID" "75B65237-534C-BD32-16BE-C39F59D2EDDA";
createNode transform -s -n "persp";
	rename -uid "CCDB11C3-7D4F-919A-B0AF-50BD926824EC";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 28 21 28 ;
	setAttr ".r" -type "double3" -27.938352729602379 44.999999999999972 -5.172681101354183e-14 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "0B51334C-7D49-9FF0-1A78-D9B5B82A1DBC";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999986;
	setAttr ".coi" 44.82186966202994;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "5658192B-8D49-6DD9-965A-F69D683F2243";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "8BBEA3E7-7E4C-0285-7967-67A8AA0479C0";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	rename -uid "4A56D4BF-5A40-1D02-BDD6-999D64907FBA";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "1983BC66-A143-23A2-0B01-4B99ECF3D695";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	rename -uid "4F3BABCD-2149-C88F-04C7-78BB4F7524EE";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "9A777275-F74F-5FEC-D1AE-57BBA47DE95C";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode transform -n "drivenSphere";
	rename -uid "1C2E304C-1D40-4A28-C86A-5C999C02E8CD";
createNode mesh -n "drivenSphereShape" -p "drivenSphere";
	rename -uid "CDF166C7-CE49-524D-72E0-F2AD0C19A2E2";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
createNode mesh -n "drivenSphereShapeOrig" -p "drivenSphere";
	rename -uid "FBDE94E4-3E4C-183A-1AB8-7886F31BB28B";
	setAttr -k off ".v";
	setAttr ".io" yes;
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
createNode transform -n "waveDriver";
	rename -uid "2DE372F8-9147-B59A-95FD-7CA2C1AF8A00";
createNode locator -n "waveDriverShape" -p "waveDriver";
	rename -uid "B6F48E9A-E945-E3B0-BD2E-7B8939E0B493";
	setAttr -k off ".v";
createNode lightLinker -s -n "lightLinker1";
	rename -uid "391581D9-1A47-6DCA-7D13-BFBFA7C9DCB8";
	setAttr -s 2 ".lnk";
	setAttr -s 2 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "5BCE54B2-D943-B0D0-2B5F-4CB7482E43B7";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "9088842A-C840-492F-65A4-EDAF25D31E81";
createNode displayLayerManager -n "layerManager";
	rename -uid "A6B98599-E848-73D1-335A-8C87FE3CB138";
createNode displayLayer -n "defaultLayer";
	rename -uid "AD310E39-F841-AAA8-EA94-D3AC36228A71";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "2B316B34-6246-B367-1A55-04BE8836FCAC";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "B05AA7DC-814C-4259-BB74-51B4EF65013E";
	setAttr ".g" yes;
createNode polySphere -n "polySphere1";
	rename -uid "A983025D-0240-BD90-68D1-55AD90547023";
	setAttr ".sa" 24;
	setAttr ".sh" 24;
createNode mPyDeformer -n "sphereWaveFromLocator";
	rename -uid "2BC41AE0-CE44-B3A2-ADCB-D1989F0BF3B0";
	addAttr -ci true -k true -sn "driverMatrix" -ln "driverMatrix" -dt "matrix";
	addAttr -ci true -k true -sn "frequency" -ln "frequency" -at "float";
	addAttr -ci true -k true -sn "amplitude" -ln "amplitude" -at "float";
	addAttr -ci true -k true -sn "falloffDistance" -ln "falloffDistance" -at "float";
	addAttr -ci true -k true -sn "offset" -ln "offset" -at "float";
	addAttr -ci true -h true -sn "_initSource" -ln "_initSource" -dt "string";
	setAttr "._computeSource" -type "string" "mesh = self.outputGeometry[0]\nrest = mesh.getPoints()\nenv = self.envelope\n# Per-vertex outward normal from sphere centroid (fast, no MFn call).\ncentroid = rest.mean(axis=0)\ndelta_v = rest - centroid.reshape(1, 3)\nmag = np.linalg.norm(delta_v, axis=1, keepdims=True)\nmag = np.where(mag < 1e-9, 1.0, mag)\nnormals = delta_v / mag\n# Driver world position lives at row 3 of the world matrix.\ndriver_mat = self.driverMatrix.asNumpy()\ndriver_pos = driver_mat[3, :3]\n# Exponential falloff -- always non-zero so any driver move produces\n# a measurable per-vertex displacement (no sine zero-crossings).\ndist = np.linalg.norm(rest - driver_pos.reshape(1, 3), axis=1, keepdims=True)\nfalloff = self.falloffDistance\nweight = np.exp(-dist / falloff)\namp = self.amplitude\nfreq = self.frequency\noff = self.offset\n# Wave along the sphere normal, modulated by driver distance.\nwave = amp * (0.5 + 0.5 * np.sin(2.0 * np.pi * freq * dist + off))\ndeformed = rest + env * weight * wave * normals\nmesh.setPoints(deformed)\n";
	setAttr "._inputAttrs" -type "string" "{\"amplitude\":{\"attr_type\":\"float\",\"is_array\":false,\"order\":2},\"driverMatrix\":{\"attr_type\":\"matrix\",\"is_array\":false,\"order\":0},\"falloffDistance\":{\"attr_type\":\"float\",\"is_array\":false,\"order\":3},\"frequency\":{\"attr_type\":\"float\",\"is_array\":false,\"order\":1},\"offset\":{\"attr_type\":\"float\",\"is_array\":false,\"order\":4}}";
	setAttr -k on ".driverMatrix";
	setAttr -k on ".frequency" 2;
	setAttr -k on ".amplitude" 0.20000000298023224;
	setAttr -k on ".falloffDistance" 3;
	setAttr "._initSource" -type "string" "import numpy as np\n";
createNode script -n "uiConfigurationScriptNode";
	rename -uid "8A7B3438-3C4F-56EF-0C5C-0DBE95623D44";
	setAttr ".b" -type "string" "// Maya Mel UI Configuration File.\n// No UI generated in batch mode.\n";
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "8DA2D51B-1F46-9184-E9CD-EB81097F627D";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 120 -ast 1 -aet 200 ";
	setAttr ".st" 6;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 3;
select -ne :renderPartition;
	setAttr -s 2 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 5 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".dss" -type "string" "standardSurface1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "sphereWaveFromLocator.og[0]" "drivenSphereShape.i";
connectAttr "polySphere1.out" "drivenSphereShapeOrig.i";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "drivenSphereShapeOrig.w" "sphereWaveFromLocator.ip[0].ig";
connectAttr "waveDriver.wm" "sphereWaveFromLocator.driverMatrix";
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
connectAttr "drivenSphereShape.iog" ":initialShadingGroup.dsm" -na;
// End of sphereWaveFromLocator.ma
