//Maya ASCII 2026 scene
//Name: MPyFile_File_Composite.ma
//Last modified: Tue, Aug 25, 2026 12:19:20 PM
//Codeset: UTF-8
requires maya "2026";
requires -nodeType "compositeTexture" "mPyMega" "1.0";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2026";
fileInfo "version" "2026";
fileInfo "cutIdentifier" "202510291147-60ec9eda33";
fileInfo "osv" "Mac OS X 20.6.2";
fileInfo "UUID" "0CAFE9DE-1C4F-582D-941A-88BFE9773308";
createNode transform -s -n "persp";
	rename -uid "9A33C6A5-8544-AE78-9290-F2BD76107D16";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 28 21 28 ;
	setAttr ".r" -type "double3" -27.938352729602379 44.999999999999972 -5.172681101354183e-14 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "C7F908A7-D94D-31C0-389E-E399369ADAAF";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 44.82186966202994;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "B3C5BB73-884D-E7A4-9ED6-EEAC9AADFF9D";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "307E6FCD-5A45-55A2-943D-749FAF9D587B";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	rename -uid "CAEF47F2-7742-5BD0-4DD3-8AB80F27A72C";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "BABA95B9-5A40-7E55-7606-D1A9CBA6661E";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	rename -uid "EE66BAC4-7849-FECC-AB61-37BE475727AA";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "BB6CC685-6D40-9AA0-8429-05B38625F08C";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode transform -n "compositeTexture_plane";
	rename -uid "E080654B-B849-485A-3398-DEB22980947D";
createNode mesh -n "compositeTexture_planeShape" -p "compositeTexture_plane";
	rename -uid "45940A83-A24F-D10E-18CC-D0BA25836812";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "37F478A5-5D4E-27F5-25D0-6886E4E5BD51";
	setAttr -s 3 ".lnk";
	setAttr -s 3 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "6D624B16-E94C-12C6-8E34-75875E1C49FD";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "F485EEF6-FD49-8377-F817-F8ABE4063284";
createNode displayLayerManager -n "layerManager";
	rename -uid "9C5FBD1D-0847-6D14-C09C-1983CD67FFCA";
createNode displayLayer -n "defaultLayer";
	rename -uid "D1E94C7A-0F40-9473-2532-3BA033957DBF";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "950426BA-8B49-A93F-05DB-529A6D69CE70";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "AE67A6CE-424F-C539-B8D2-CDB66C4A2263";
	setAttr ".g" yes;
createNode polyPlane -n "polyPlane1";
	rename -uid "028C4032-6C4B-B2FA-5986-E0B48EAEC0C6";
	setAttr ".w" 10;
	setAttr ".h" 10;
	setAttr ".sw" 1;
	setAttr ".sh" 1;
createNode surfaceShader -n "compositeTexture_surface";
	rename -uid "B58D2143-9547-460A-BBB7-D69A8E24C4F0";
createNode shadingEngine -n "compositeTexture_surfaceSG";
	rename -uid "08A4686C-0D49-D153-8FE0-FCAEE4FD9B05";
	setAttr ".ihi" 0;
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo1";
	rename -uid "831C6CAD-5445-B1BE-B787-5EA14F5C7D3B";
createNode compositeTexture -n "compositeTexture";
	rename -uid "DFACE6F0-6C43-5091-0FA3-FCB2BE0100FB";
	setAttr ".fileName" -type "string" "";
	setAttr -s 4 ".layers";
	setAttr ".layers[0]" -type "string" "/Users/ericvignola/Documents/node-designer2-file/MPyNode/templates/MPyFile/File Composite/grid_bg.png";
	setAttr ".layers[1]" -type "string" "/Users/ericvignola/Documents/node-designer2-file/MPyNode/templates/MPyFile/File Composite/red_square.png";
	setAttr ".layers[2]" -type "string" "/Users/ericvignola/Documents/node-designer2-file/MPyNode/templates/MPyFile/File Composite/green_circle.png";
	setAttr ".layers[3]" -type "string" "/Users/ericvignola/Documents/node-designer2-file/MPyNode/templates/MPyFile/File Composite/blue_triangle.png";
	setAttr ".preFilterRadius" 2;
createNode script -n "uiConfigurationScriptNode";
	rename -uid "C8573E2E-974F-8EA2-665E-E9B0E38FB920";
	setAttr ".b" -type "string" "// Maya Mel UI Configuration File.\n// No UI generated in batch mode.\n";
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "77C43EFD-524F-3B19-0EB7-C8903DF319D5";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 120 -ast 1 -aet 200 ";
	setAttr ".st" 6;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 3;
select -ne :renderPartition;
	setAttr -s 3 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 7 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :openPBR_shader1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".dss" -type "string" "openPBR_shader1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "polyPlane1.out" "compositeTexture_planeShape.i";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "compositeTexture_surfaceSG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "compositeTexture_surfaceSG.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "compositeTexture.outColor" "compositeTexture_surface.oc";
connectAttr "compositeTexture_surface.oc" "compositeTexture_surfaceSG.ss";
connectAttr "compositeTexture_planeShape.iog" "compositeTexture_surfaceSG.dsm" -na
		;
connectAttr "compositeTexture_surfaceSG.msg" "materialInfo1.sg";
connectAttr "compositeTexture_surfaceSG.pa" ":renderPartition.st" -na;
connectAttr "compositeTexture_surface.msg" ":defaultShaderList1.s" -na;
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
// End of MPyFile_File_Composite.ma
