//Maya ASCII 2026 scene
//Name: MPyFile_Game_Of_Life_Texture.ma
//Last modified: Wed, Aug 26, 2026 08:14:43 PM
//Codeset: UTF-8
requires maya "2026";
requires -nodeType "gameOfLifeTex" "mPyMega" "1.0";
requires -nodeType "aiStandardSurface" -nodeType "aiOslShader" "mtoa" "5.5.4.2";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2026";
fileInfo "version" "2026";
fileInfo "cutIdentifier" "202510291147-60ec9eda33";
fileInfo "osv" "Mac OS X 20.6.2";
fileInfo "UUID" "0E13E1D1-244B-943C-5A6F-EA97DF975129";
createNode transform -s -n "persp";
	rename -uid "FDBFC9C5-154F-9047-7420-82B217851F7D";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 28 21 28 ;
	setAttr ".r" -type "double3" -27.938352729602379 44.999999999999972 -5.172681101354183e-14 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "B5343F17-1A4A-2CB1-0CE5-9D89DEC3E53C";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 44.82186966202994;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "2B425B79-CC4A-32E0-E95F-B39E27CD3878";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "7E6DDB0B-744D-618F-8FC5-AEAC72D22A49";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	rename -uid "DFE185BD-1340-CA53-02A6-3DA681AD5B85";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "0C8DE775-434F-E823-39A6-5DACED74CB8F";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	rename -uid "10C70DC3-914D-71EA-02BD-3F8FAC86A02A";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "7FFC75BA-E340-6E05-12D7-9DA55C03B72A";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode transform -n "gameOfLifeTex_plane";
	rename -uid "221167B7-8B40-EE18-A838-3EBA436AC488";
createNode mesh -n "gameOfLifeTex_planeShape" -p "gameOfLifeTex_plane";
	rename -uid "B914670A-1948-8C35-2E33-07ACC9969238";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "332B9BE9-D14C-1DBB-3828-49A1EC7471D8";
	setAttr -s 3 ".lnk";
	setAttr -s 3 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "D5B89A6F-A74A-A794-1206-CF84D81AC1BA";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "137BB3DC-C244-F321-C4F3-4CBA07853722";
createNode displayLayerManager -n "layerManager";
	rename -uid "1909893E-1543-D1A8-9B84-549058B1CAE2";
createNode displayLayer -n "defaultLayer";
	rename -uid "E2133EE4-0148-404C-FB9E-23814F27A0AC";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "DD906A89-E642-7BDB-CF85-E2872B512D39";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "21E189B4-4546-53DC-DB9C-0397B5DCBD5F";
	setAttr ".g" yes;
createNode polyPlane -n "polyPlane1";
	rename -uid "2FB265A2-3641-5F6F-70E0-538BC97B2D3F";
	setAttr ".w" 10;
	setAttr ".h" 10;
	setAttr ".sw" 1;
	setAttr ".sh" 1;
createNode lambert -n "gameOfLifeTex_lambert";
	rename -uid "CCDAC009-A641-0418-A421-81B1F5F042AC";
createNode shadingEngine -n "gameOfLifeTex_lambertSG";
	rename -uid "1FAF08D8-C746-F10C-11AE-AE9C41F29D27";
	setAttr ".ihi" 0;
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo1";
	rename -uid "13D0FFB4-FC4F-3B1C-B9CE-97A35BEF9DBF";
createNode aiOslShader -n "gameOfLifeTex_arnoldOsl";
	rename -uid "BD22A6B9-ED40-3BD4-0EA4-8B833056597D";
	addAttr -r false -ci true -sn "paramFileName" -ln "fileName" -ct "oslAttribute" 
		-dt "string";
	addAttr -r false -ci true -sn "paramBakeFrame" -ln "bakeFrame" -ct "oslAttribute" 
		-at "float";
	addAttr -w false -uac -sn "paramOutColor" -ln "outColor" -ct "oslAttribute" -at "float3" 
		-nc 3;
	addAttr -w false -sn "paramOutColorR" -ln "outColorR" -at "float" -p "outColor";
	addAttr -w false -sn "paramOutColorG" -ln "outColorG" -at "float" -p "outColor";
	addAttr -w false -sn "paramOutColorB" -ln "outColorB" -at "float" -p "outColor";
	addAttr -w false -sn "paramOutAlpha" -ln "outAlpha" -ct "oslAttribute" -at "float";
	setAttr ".code" -type "string" (
		"// ----------------------------------------------------------------------\n// gameOfLife -- OSL shader (Open Shading Language) for Arnold.\n//\n// Game of Life is a STATEFUL simulation, so -- unlike a closed-form texture --\n// it cannot be evaluated from (u, v, time) alone. Instead the node BAKES the\n// current board to an image each frame (a \"virtual texture that regenerates\n// every frame\") and this shader simply samples that file. `fileName` is set by\n// the node's setup to the per-node baked PNG.\n//\n// The bake is a FRAME SEQUENCE, not one overwritten file, and this shader\n// rebuilds the per-frame name from `fileName` + `bakeFrame`. That is not a\n// stylistic choice: Arnold's texture system caches by filename and never\n// re-stats, so a node that re-bakes one fixed path renders whichever frame\n// Arnold happened to read first -- forever. `bakeFrame` is driven from the\n// node's `frame` input by the setup, which also gives MtoA an animated\n// parameter to re-translate. The name rule mirrors os.path.splitext exactly,\n"
		+ "// because the Compute tier (Python) and the nd_tex_write C++ kernel build the\n// same string: \"x.png\" + 7 -> \"x.0007.png\".\n//\n// NEAREST (\"closest\") filtering keeps the cells crisp; the (1 - v) flip matches\n// the Compute tab so the Arnold render lines up with the swatch / viewport. The\n// board is pure black/white, so NO sRGB->linear step is needed (0 and 1 are\n// fixed points of the transfer curve, unlike the file_brightness_contrast OSL).\n// ----------------------------------------------------------------------\nshader gameOfLife(\n    string fileName = \"\",\n    float bakeFrame = 0,\n    output color outColor = color(0),\n    output float outAlpha = 1.0)\n{\n    // The node always bakes PNGs, so only that suffix needs stripping.\n    string base = fileName;\n    int n = strlen(base);\n    if (n > 4 && substr(base, n - 4, 4) == \".png\") {\n        base = substr(base, 0, n - 4);\n    }\n    string path = format(\"%s.%04d.png\", base, int(bakeFrame));\n    color c = texture(path, u, 1.0 - v, \"interp\", \"closest\",\n                      \"wrap\", \"clamp\");\n"
		+ "    outColor = c;\n    outAlpha = 1.0;\n}\n");
	setAttr ".paramFileName" -type "string" "/var/folders/0d/x47rzb2533d_3qc6jf32l8s40000gn/T/mpy_gol_gameOfLifeTex.png";
createNode timeToUnitConversion -n "timeToUnitConversion1";
	rename -uid "93D9C60F-8542-2541-BE41-4E8DCD63F8C3";
	setAttr ".cf" 0.004;
createNode aiStandardSurface -n "gameOfLifeTex_arnoldMtl";
	rename -uid "946FD655-9241-1FD0-130B-4986DA4625B7";
	setAttr ".specular" 0;
createNode gameOfLifeTex -n "gameOfLifeTex";
	rename -uid "AA5E5140-2E45-815B-16FB-079089892AA5";
	setAttr ".bakePath" -type "string" "/var/folders/0d/x47rzb2533d_3qc6jf32l8s40000gn/T/mpy_gol_gameOfLifeTex.png";
	setAttr ".fileName" -type "string" "";
	setAttr ".osl" -type "string" (
		"// ----------------------------------------------------------------------\n// gameOfLife -- OSL shader (Open Shading Language) for Arnold.\n//\n// Game of Life is a STATEFUL simulation, so -- unlike a closed-form texture --\n// it cannot be evaluated from (u, v, time) alone. Instead the node BAKES the\n// current board to an image each frame (a \"virtual texture that regenerates\n// every frame\") and this shader simply samples that file. `fileName` is set by\n// the node's setup to the per-node baked PNG.\n//\n// The bake is a FRAME SEQUENCE, not one overwritten file, and this shader\n// rebuilds the per-frame name from `fileName` + `bakeFrame`. That is not a\n// stylistic choice: Arnold's texture system caches by filename and never\n// re-stats, so a node that re-bakes one fixed path renders whichever frame\n// Arnold happened to read first -- forever. `bakeFrame` is driven from the\n// node's `frame` input by the setup, which also gives MtoA an animated\n// parameter to re-translate. The name rule mirrors os.path.splitext exactly,\n"
		+ "// because the Compute tier (Python) and the nd_tex_write C++ kernel build the\n// same string: \"x.png\" + 7 -> \"x.0007.png\".\n//\n// NEAREST (\"closest\") filtering keeps the cells crisp; the (1 - v) flip matches\n// the Compute tab so the Arnold render lines up with the swatch / viewport. The\n// board is pure black/white, so NO sRGB->linear step is needed (0 and 1 are\n// fixed points of the transfer curve, unlike the file_brightness_contrast OSL).\n// ----------------------------------------------------------------------\nshader gameOfLife(\n    string fileName = \"\",\n    float bakeFrame = 0,\n    output color outColor = color(0),\n    output float outAlpha = 1.0)\n{\n    // The node always bakes PNGs, so only that suffix needs stripping.\n    string base = fileName;\n    int n = strlen(base);\n    if (n > 4 && substr(base, n - 4, 4) == \".png\") {\n        base = substr(base, 0, n - 4);\n    }\n    string path = format(\"%s.%04d.png\", base, int(bakeFrame));\n    color c = texture(path, u, 1.0 - v, \"interp\", \"closest\",\n                      \"wrap\", \"clamp\");\n"
		+ "    outColor = c;\n    outAlpha = 1.0;\n}\n");
createNode script -n "uiConfigurationScriptNode";
	rename -uid "5DBDB68A-B04C-4730-F377-1489AE919C8F";
	setAttr ".b" -type "string" "// Maya Mel UI Configuration File.\n// No UI generated in batch mode.\n";
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "56659A98-F64A-EC0D-A080-0CACE49DE40A";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 120 -ast 1 -aet 200 ";
	setAttr ".st" 6;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 3;
select -ne :renderPartition;
	setAttr -s 3 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 8 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :openPBR_shader1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".dss" -type "string" "openPBR_shader1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "polyPlane1.out" "gameOfLifeTex_planeShape.i";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "gameOfLifeTex_lambertSG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "gameOfLifeTex_lambertSG.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "gameOfLifeTex.outColor" "gameOfLifeTex_lambert.c";
connectAttr "gameOfLifeTex_lambert.oc" "gameOfLifeTex_lambertSG.ss";
connectAttr "gameOfLifeTex_planeShape.iog" "gameOfLifeTex_lambertSG.dsm" -na;
connectAttr "gameOfLifeTex_arnoldMtl.out" "gameOfLifeTex_lambertSG.ai_surface_shader"
		;
connectAttr "gameOfLifeTex_lambertSG.msg" "materialInfo1.sg";
connectAttr "gameOfLifeTex.osl" "gameOfLifeTex_arnoldOsl.code_cache";
connectAttr "timeToUnitConversion1.o" "gameOfLifeTex_arnoldOsl.paramBakeFrame";
connectAttr "gameOfLifeTex.frame" "timeToUnitConversion1.i";
connectAttr "gameOfLifeTex_arnoldOsl.paramOutColor" "gameOfLifeTex_arnoldMtl.base_color"
		;
connectAttr ":time1.o" "gameOfLifeTex._timeIn";
connectAttr ":time1.o" "gameOfLifeTex.frame";
connectAttr "gameOfLifeTex_lambertSG.pa" ":renderPartition.st" -na;
connectAttr "gameOfLifeTex_lambert.msg" ":defaultShaderList1.s" -na;
connectAttr "gameOfLifeTex_arnoldMtl.msg" ":defaultShaderList1.s" -na;
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
// End of MPyFile_Game_Of_Life_Texture.ma
