//Maya ASCII 2026 scene
//Name: MPyFile_File_Scanline.ma
//Last modified: Tue, Aug 25, 2026 12:19:28 PM
//Codeset: UTF-8
requires maya "2026";
requires -nodeType "scanlineTex" "mPyMega" "1.0";
requires -nodeType "aiStandardSurface" -nodeType "aiOslShader" "mtoa" "5.5.4.2";
currentUnit -l centimeter -a degree -t film;
fileInfo "application" "maya";
fileInfo "product" "Maya 2026";
fileInfo "version" "2026";
fileInfo "cutIdentifier" "202510291147-60ec9eda33";
fileInfo "osv" "Mac OS X 20.6.2";
fileInfo "UUID" "310A3F46-0E41-56A1-CCFF-CD9136D17814";
createNode transform -s -n "persp";
	rename -uid "421DBB51-474F-96FE-90DA-9BAD7AFFD398";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 28 21 28 ;
	setAttr ".r" -type "double3" -27.938352729602379 44.999999999999972 -5.172681101354183e-14 ;
createNode camera -s -n "perspShape" -p "persp";
	rename -uid "811A2A13-8044-B420-34E4-77B3774E0C6C";
	setAttr -k off ".v" no;
	setAttr ".fl" 34.999999999999993;
	setAttr ".coi" 44.82186966202994;
	setAttr ".imn" -type "string" "persp";
	setAttr ".den" -type "string" "persp_depth";
	setAttr ".man" -type "string" "persp_mask";
	setAttr ".hc" -type "string" "viewSet -p %camera";
createNode transform -s -n "top";
	rename -uid "DDBCD4BB-C543-0176-86F3-939194F173CA";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 1000.1 0 ;
	setAttr ".r" -type "double3" -89.999999999999986 0 0 ;
createNode camera -s -n "topShape" -p "top";
	rename -uid "70CA6E8D-6B4A-0923-72FE-70B2C8684CE6";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "top";
	setAttr ".den" -type "string" "top_depth";
	setAttr ".man" -type "string" "top_mask";
	setAttr ".hc" -type "string" "viewSet -t %camera";
	setAttr ".o" yes;
createNode transform -s -n "front";
	rename -uid "59D56C15-BE4E-ECDC-7F5A-838F8A99D534";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 0 0 1000.1 ;
createNode camera -s -n "frontShape" -p "front";
	rename -uid "2AA2C52B-5E4D-55B2-D2CF-259443F16D9A";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "front";
	setAttr ".den" -type "string" "front_depth";
	setAttr ".man" -type "string" "front_mask";
	setAttr ".hc" -type "string" "viewSet -f %camera";
	setAttr ".o" yes;
createNode transform -s -n "side";
	rename -uid "F4077F14-DD41-B146-581A-03A3FD2BDECA";
	setAttr ".v" no;
	setAttr ".t" -type "double3" 1000.1 0 0 ;
	setAttr ".r" -type "double3" 0 89.999999999999986 0 ;
createNode camera -s -n "sideShape" -p "side";
	rename -uid "2AA4CEA0-1144-7E9D-6980-DF81719D2FE0";
	setAttr -k off ".v" no;
	setAttr ".rnd" no;
	setAttr ".coi" 1000.1;
	setAttr ".ow" 30;
	setAttr ".imn" -type "string" "side";
	setAttr ".den" -type "string" "side_depth";
	setAttr ".man" -type "string" "side_mask";
	setAttr ".hc" -type "string" "viewSet -s %camera";
	setAttr ".o" yes;
createNode transform -n "scanlineTex_plane";
	rename -uid "FF1B0514-8E4C-9E05-F663-AAB5B78EE140";
createNode mesh -n "scanlineTex_planeShape" -p "scanlineTex_plane";
	rename -uid "D96F5574-F149-DFB5-374C-FA8F4B309169";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr ".cuvs" -type "string" "map1";
	setAttr ".dcc" -type "string" "Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr ".ndt" 0;
createNode lightLinker -s -n "lightLinker1";
	rename -uid "5E0B7A61-5447-2D11-FF14-ECAF49EDCF27";
	setAttr -s 3 ".lnk";
	setAttr -s 3 ".slnk";
createNode shapeEditorManager -n "shapeEditorManager";
	rename -uid "73D7CFF0-B144-F154-82C7-DC91BFAAE527";
createNode poseInterpolatorManager -n "poseInterpolatorManager";
	rename -uid "94C9D4A1-A545-89DB-5168-C280676F7020";
createNode displayLayerManager -n "layerManager";
	rename -uid "327C0ECC-3048-D01B-296F-4D97AA49D035";
createNode displayLayer -n "defaultLayer";
	rename -uid "7354D0E3-8948-4BC6-849C-32996DD83169";
	setAttr ".ufem" -type "stringArray" 0  ;
createNode renderLayerManager -n "renderLayerManager";
	rename -uid "0884E182-744F-AE7C-5932-93A64C37D40C";
createNode renderLayer -n "defaultRenderLayer";
	rename -uid "DA4C80AA-C546-604D-15D4-0DBF5FE8A193";
	setAttr ".g" yes;
createNode polyPlane -n "polyPlane1";
	rename -uid "D18ED3FE-E047-17BF-8487-749948752922";
	setAttr ".w" 10;
	setAttr ".h" 10;
	setAttr ".sw" 1;
	setAttr ".sh" 1;
createNode surfaceShader -n "scanlineTex_surface";
	rename -uid "B251CCBD-4043-7CA9-0DE9-A8A255E963D5";
createNode shadingEngine -n "scanlineTex_surfaceSG";
	rename -uid "4D62D183-7648-78B9-0E73-C7A0FD7696C5";
	setAttr ".ihi" 0;
	setAttr ".ro" yes;
createNode materialInfo -n "materialInfo1";
	rename -uid "81DEFBA2-C348-C875-2AE1-209A43C05295";
createNode aiOslShader -n "scanlineTex_arnoldOsl";
	rename -uid "3ECB955A-4F45-7CF4-B5F5-94ABBE0C5B3A";
	addAttr -r false -ci true -sn "paramFileName" -ln "fileName" -ct "oslAttribute" 
		-dt "string";
	addAttr -r false -ci true -sn "paramBands" -ln "bands" -ct "oslAttribute" -dv 12 
		-at "float";
	addAttr -r false -ci true -sn "paramSpeed" -ln "speed" -ct "oslAttribute" -dv 0.10000000149011612 
		-at "float";
	addAttr -r false -ci true -sn "paramIntensity" -ln "intensity" -ct "oslAttribute" 
		-dv 0.60000002384185791 -at "float";
	addAttr -r false -ci true -sn "paramTIn" -ln "tIn" -ct "oslAttribute" -at "float";
	addAttr -w false -uac -sn "paramOutColor" -ln "outColor" -ct "oslAttribute" -at "float3" 
		-nc 3;
	addAttr -w false -sn "paramOutColorR" -ln "outColorR" -at "float" -p "outColor";
	addAttr -w false -sn "paramOutColorG" -ln "outColorG" -at "float" -p "outColor";
	addAttr -w false -sn "paramOutColorB" -ln "outColorB" -at "float" -p "outColor";
	addAttr -w false -sn "paramOutAlpha" -ln "outAlpha" -ct "oslAttribute" -at "float";
	setAttr ".code" -type "string" (
		"// ----------------------------------------------------------------------\n// scanlineTex -- OSL twin of the scanline Compute look. Wire into an\n// aiOslShader (Arnold) so the renderer reproduces the scrolling scan bands.\n// Mirrors Compute: sample with the (1 - v) flip, linearize sRGB->scene-linear\n// (Arnold's texture() returns RAW sRGB), then multiply by the scan factor.\n// ----------------------------------------------------------------------\ncolor srgb_to_linear(color c)\n{\n    color lo = c / 12.92;\n    color hi = pow(max((c + color(0.055)) / 1.055, color(0.0)), 2.4);\n    return mix(lo, hi, step(color(0.04045), c));\n}\n\nshader scanlineTex(\n    string fileName = \"\",\n    float bands = 12.0,\n    float speed = 0.1,\n    float intensity = 0.6,\n    float tIn = 0.0,\n    output color outColor = color(0),\n    output float outAlpha = 1.0)\n{\n    float a = 1.0;\n    color c = texture(fileName, u, 1.0 - v, \"alpha\", a);\n    c = srgb_to_linear(c);\n    float s = 0.5 + 0.5 * sin((v * bands - tIn * speed) * 6.283185307179586);\n"
		+ "    float scan = (1.0 - intensity) + intensity * s;\n    outColor = clamp(c * scan, color(0), color(1));\n    outAlpha = a;\n}\n");
	setAttr ".code_cache" -type "string" (
		"// ----------------------------------------------------------------------\n// scanlineTex -- OSL twin of the scanline Compute look. Wire into an\n// aiOslShader (Arnold) so the renderer reproduces the scrolling scan bands.\n// Mirrors Compute: sample with the (1 - v) flip, linearize sRGB->scene-linear\n// (Arnold's texture() returns RAW sRGB), then multiply by the scan factor.\n// ----------------------------------------------------------------------\ncolor srgb_to_linear(color c)\n{\n    color lo = c / 12.92;\n    color hi = pow(max((c + color(0.055)) / 1.055, color(0.0)), 2.4);\n    return mix(lo, hi, step(color(0.04045), c));\n}\n\nshader scanlineTex(\n    string fileName = \"\",\n    float bands = 12.0,\n    float speed = 0.1,\n    float intensity = 0.6,\n    float tIn = 0.0,\n    output color outColor = color(0),\n    output float outAlpha = 1.0)\n{\n    float a = 1.0;\n    color c = texture(fileName, u, 1.0 - v, \"alpha\", a);\n    c = srgb_to_linear(c);\n    float s = 0.5 + 0.5 * sin((v * bands - tIn * speed) * 6.283185307179586);\n"
		+ "    float scan = (1.0 - intensity) + intensity * s;\n    outColor = clamp(c * scan, color(0), color(1));\n    outAlpha = a;\n}\n");
	setAttr ".paramFileName" -type "string" "/Users/ericvignola/Documents/node-designer2-file/MPyNode/templates/MPyFile/File Scanline/test_grid.png";
createNode timeToUnitConversion -n "timeToUnitConversion1";
	rename -uid "89AD853A-2248-3DB5-B290-1AB8C85255DB";
	setAttr ".cf" 0.004;
createNode aiStandardSurface -n "scanlineTex_arnoldMtl";
	rename -uid "5CB56654-E747-0CCB-E901-008DA1526B3E";
	setAttr ".specular" 0;
createNode scanlineTex -n "scanlineTex";
	rename -uid "0058E93E-674F-69CF-D4C7-CDBC1FAA12DD";
	setAttr ".fileName" -type "string" "/Users/ericvignola/Documents/node-designer2-file/MPyNode/templates/MPyFile/File Scanline/test_grid.png";
	setAttr ".preFilterRadius" 2;
createNode script -n "uiConfigurationScriptNode";
	rename -uid "524CE8DE-E540-8C3F-5758-8A8183B85FDF";
	setAttr ".b" -type "string" "// Maya Mel UI Configuration File.\n// No UI generated in batch mode.\n";
	setAttr ".st" 3;
createNode script -n "sceneConfigurationScriptNode";
	rename -uid "4E9D7203-B04A-BD83-1E39-D8BA19255279";
	setAttr ".b" -type "string" "playbackOptions -min 1 -max 120 -ast 1 -aet 120 ";
	setAttr ".st" 6;
select -ne :time1;
	setAttr ".o" 1;
	setAttr ".unw" 1;
select -ne :hardwareRenderingGlobals;
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 3;
select -ne :renderPartition;
	setAttr -s 3 ".st";
select -ne :renderGlobalsList1;
select -ne :defaultShaderList1;
	setAttr -s 8 ".s";
select -ne :postProcessList1;
	setAttr -s 2 ".p";
select -ne :defaultRenderingList1;
select -ne :standardSurface1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :openPBR_shader1;
	setAttr ".bc" -type "float3" 0.40000001 0.40000001 0.40000001 ;
	setAttr ".sr" 0.5;
select -ne :initialShadingGroup;
	setAttr ".ro" yes;
select -ne :initialParticleSE;
	setAttr ".ro" yes;
select -ne :defaultRenderGlobals;
	addAttr -ci true -h true -sn "dss" -ln "defaultSurfaceShader" -dt "string";
	setAttr ".dss" -type "string" "openPBR_shader1";
select -ne :defaultResolution;
	setAttr ".pa" 1;
select -ne :defaultColorMgtGlobals;
	setAttr ".cfe" yes;
	setAttr ".cfp" -type "string" "<MAYA_RESOURCES>/OCIO-configs/Maya2022-default/config.ocio";
	setAttr ".vtn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".vn" -type "string" "ACES 1.0 SDR-video";
	setAttr ".dn" -type "string" "sRGB";
	setAttr ".wsn" -type "string" "ACEScg";
	setAttr ".otn" -type "string" "ACES 1.0 SDR-video (sRGB)";
	setAttr ".potn" -type "string" "ACES 1.0 SDR-video (sRGB)";
select -ne :hardwareRenderGlobals;
	setAttr ".ctrs" 256;
	setAttr ".btrs" 512;
connectAttr "polyPlane1.out" "scanlineTex_planeShape.i";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "scanlineTex_surfaceSG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "scanlineTex_surfaceSG.message" ":defaultLightSet.message";
connectAttr "layerManager.dli[0]" "defaultLayer.id";
connectAttr "renderLayerManager.rlmi[0]" "defaultRenderLayer.rlid";
connectAttr "scanlineTex.outColor" "scanlineTex_surface.oc";
connectAttr "scanlineTex_surface.oc" "scanlineTex_surfaceSG.ss";
connectAttr "scanlineTex_planeShape.iog" "scanlineTex_surfaceSG.dsm" -na;
connectAttr "scanlineTex_arnoldMtl.out" "scanlineTex_surfaceSG.ai_surface_shader"
		;
connectAttr "scanlineTex_surfaceSG.msg" "materialInfo1.sg";
connectAttr "timeToUnitConversion1.o" "scanlineTex_arnoldOsl.paramTIn";
connectAttr ":time1.o" "timeToUnitConversion1.i";
connectAttr "scanlineTex_arnoldOsl.paramOutColor" "scanlineTex_arnoldMtl.base_color"
		;
connectAttr ":time1.o" "scanlineTex.frame";
connectAttr "scanlineTex_surfaceSG.pa" ":renderPartition.st" -na;
connectAttr "scanlineTex_surface.msg" ":defaultShaderList1.s" -na;
connectAttr "scanlineTex_arnoldMtl.msg" ":defaultShaderList1.s" -na;
connectAttr "defaultRenderLayer.msg" ":defaultRenderingList1.r" -na;
// End of MPyFile_File_Scanline.ma
