from mpylib.api.openmaya import (
    MAngle,
    MColor,
    MColorArray,
    MEulerRotation,
    MFnNurbsCurve,
    MMatrix,
    MMatrixArray,
    MPoint,
    MPointArray,
    MQuaternion,
    MTime,
    MTimeArray,
    MVector,
    MVectorArray,
)
